FROM node:20-bookworm-slim

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY tsconfig.json tsconfig.spec.json jest.config.js ./
COPY src ./src
COPY test ./test
COPY scripts ./scripts

CMD ["yarn", "test"]
